### ISSUE TITLE
Setup failed on Link fatal error

### ISSUE THREAD

**Issue by AndurilLi** [kivy/pyjnius#125]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

E:\software\python\pyjnius-master>ls
LICENSE      Makefile     build        jnius        tests
MANIFEST.in  README.md    docs         setup.py

E:\software\python\pyjnius-master>python setup.py install
C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option:
 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running build_ext
skipping 'jnius\jnius.c' Cython extension (up-to-date)
building 'jnius' extension
C:\VS9\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program Files (x
86)\Java\jdk1.6.0_38\include" "-IC:\Program Files (x86)\Java\jdk1.6.0_38\include
\win32" -IC:\Python27\include -IC:\Python27\PC /Tcjnius\jnius.c /Fobuild\temp.wi
n32-2.7\Release\jnius\jnius.obj
jnius.c
jnius\jnius.c(3384) : warning C4047: 'function' : 'void *_' differs in levels of
 indirection from 'JNIEnv *_'
jnius\jnius.c(3384) : warning C4022: 'function through pointer' : pointer mismat
ch for actual parameter 2
jnius\jnius.c(13265) : warning C4047: '=' : 'jobject' differs in levels of indir
ection from 'jobject *'
jnius\jnius.c(13274) : warning C4047: '=' : 'jobject' differs in levels of indir
ection from 'jclass *'
C:\VS9\VC\BIN\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:C:\Program Files (
x86)\Java\jdk1.6.0_38\lib" "/LIBPATH:C:\Program Files (x86)\Java\jdk1.6.0_38\jre
\bin\server" /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild jvm.lib /EXP
ORT:initjnius build\temp.win32-2.7\Release\jnius\jnius.obj /OUT:build\lib.win32-
2.7\jnius\jnius.pyd /IMPLIB:build\temp.win32-2.7\Release\jnius\jnius.lib /MANIFE
STFILE:build\temp.win32-2.7\Release\jnius\jnius.pyd.manifest -Wl,-rpath "C:\Prog
ram Files (x86)\Java\jdk1.6.0_38\lib"
LINK : warning LNK4044: unrecognized option '/Wl,-rpath'; ignored
LINK : fatal error LNK1181: cannot open input file 'C:\Program Files (x86)\Java\
jdk1.6.0_38\lib.obj'
error: command 'C:\VS9\VC\BIN\link.exe' failed with exit status 1181

I don't find such file lib.obj in google and not sure why it happens.
##

**Comment by maazali1** [comment]
I am also experiencing the same issue. How to resolve this???

**Comment by sajadbanooie** [comment]
same about me

**Comment by remram44** [comment]
In [setup.py line 97](https://github.com/kivy/pyjnius/blob/master/setup.py#L97), replace:
```
extra_link_args = ['-Wl,-rpath', library_dirs[0]]
```
with:
```
extra_link_args = ['/LIBDIR:%s' % library_dirs[0]]
```

**Comment by sajadbanooie** [comment]
i tried that but now the exit status is 1120

**Comment by remram44** [comment]
I can't tell what's wrong just from MSVC's exit status. This is the change I made when I installed it, it was sufficient on my machine.

**Comment by gembolf** [comment]
same problem here, unlike advised by @remram44 i changed to:
`extra_link_args = ['/LIBPATH:%s' % library_dirs[0]]`
(/LIBDIR was reported by my link.exe as unrecognized parameter warning)
and I am now getting:
`jnius.obj : error LNK2019: unresolved external symbol __imp__JNI_CreateJavaVM@12 referenced in function ___pyx_f_5jnius_create_jnienvbuild\lib.win32-2.7\jnius\jnius.pyd : fatal error LNK1120: 1 unresolved externals`

strangely enough, this symbol is supposed to be linked from jvm.lib, which should be linked thanks to sequence starting from line 92 in setup.py:
`    library_dirs = [join(jdk_home, 'lib'), join(jre_home, 'bin', 'server')]`
`    libraries = ['jvm']`

I am getting stuck here with no more ideas, since both jvm.lib and jvm.dll should be easily accesible as paths to both are present in my link parameters:

`link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:C:\Program Files\Java\jdk1.8.0_31\lib" "/LIBPATH:C:\Program Files\Java\jdk1.8.0_31\jre\bin\server" /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild jvm.lib /EXPORT:initjnius build\temp.win32-2.7\Release\jnius\jnius.obj /OUT:build\lib.win32-2.7\jnius\jnius.pyd /IMPLIB:build\temp.win32-2.7\Release\jnius\jnius.lib /MANIFESTFILE:build\temp.win32-2.7\Release\jnius\jnius.pyd.manifest "/LIBPATH:C:\Program Files\Java\jdk1.8.0_31\lib"`

platform is Win7 64b

**Comment by remram44** [comment]
LIBPATH doesn't mean the same as LIBDIR. You'll have to adjust paths.

**Comment by martinsun** [comment]
@remram44 is correct 
my enviroment is  below:
python 2.7.10  32bit    
jdk 1.7.0_80 32bit
cython 0.23

**Comment by azamzubairi** [comment]
extra_link_args = ['/LIBDIR:%s' % library_dirs[0]]

This worked fine for me. Everything working smoothly now. 
Thanks @remram44

For those still experiencing issues should look into their environment variables they should be in order. There are several java paths which have to be set before installation

**Comment by dschiller** [comment]
Try to check your Python Architecture Version against your JDK Version. I have the same issue here by using Python 2.7.x 32 Bit ( Run `python` to see which Architecture you're using ). I fixed it by uninstalling Python 2.7.x 32 Bit and install Python 2.7.x 64 Bit ( eg. `python-2.7.11.amd64.msi` ) because my JDK I need for `cython` and `PyJnius` is 64 Bit. Maybe the Issue here is a Architecture Mismatch. To finally get it right you need to get rid of the installed `cython` Version ( `pip uninstall cython` ) because it's the 32 Bit Version and install it again ( `pip install cython` ) to get the 64 Bit Version. Now you should be able to install `pyjnius` ( `pip install pyjnius` ) without any trouble.

**Comment by nutchynicha** [comment]
@remram44 
I have the same problem. where did you replace : extra_link_args = ['-Wl,-rpath', library_dirs[0]]

I mean. Where is setup.py

**Comment by tshirtman** [comment]
pyjnius is now available as a wheel, and the packaging evolved quite a bit since this issue was opened, i'm going to close it, in case there are still problem, it would be better to open a new issue.
