### ISSUE TITLE
Installing pyjinius on windows 8

### ISSUE THREAD

**Issue by fera0013** [kivy/pyjnius#147]
Hi, 

I am using an Anaconda distribution on windows 8 and I have no idea, how to install pyjinius. 

Can you help me?
##

**Comment by AdamAtri** [comment]
I have Win7 (with python 2.7.9) not Win8 but these are the directions that I followed:

This is a really good tutorial for building Python with Visual Studio:
http://p-nand-q.com/python/building-python-27-with-vs2010.html
And you need to do this because otherwise jnius throws an exception indicating that it can't find the python debug files.

DOWNLOAD - 
   Source files for the Python distribution you want to use. You are going to have to build the debug files - instructions to come. At the end you will still install the msi from Python directly, but you'll replace the files in the install directory with those you have built (See the tutorial above). Below you'll find some things that are not manifestly obvious from the tutorial.

INSTALL - 
   Visual Studio 2008 or higher
   MS Visual C++ 2010 Redistributable Package (x86)
              (www.microsoft.com/en-us/download/details.aspx?id=5555)
   Java JDK (I installed java 7.75) 
   GnuWin32 Make (http://gnuwin32.sourceforge.net/packages/make.htm)
   Python* (2.7.9 or higher comes with PIP installed)
              pip install cython==0.19.2
   *Wait to install python until the very end, after you have finished building the debug files from the tutorial above !!!
   *If you already have Python installed, you may have to uninstall

ADD ENVIRONMENT VARIABLES- 
- PYTHON_HOME (python install directory, C:\Python<ver.>)
- PYTHON_SCRIPTS (%PYTHON_HOME%\Scripts)
- PYTHONPATH (%PYTHON_HOME%; %PYTHON_HOME%\DLLs; %PYTHON_HOME%\Lib;   %PYTHON_HOME%\Tools; %PYTHON_SCRIPTS%;)
- JDK_HOME
- JRE_HOME
- JAVA_HOME (=JDK_HOME but make both)
- GNU_HOME (GnuWin32 install dir)

ADD TO path - 
   %PYTHON_HOME%; %PYTHON_SCRIPTS%; %JAVA_HOME%; %JAVA_HOME%\bin; %JAVA_HOME%\jre\bin\server; %GNU_HOME%\bin
++++++++++++++++++++++++++++++++++++++++++++++++
Now that the preliminaries are out of the way you should be able to download the pyjnius source and make the makefile. Simple right?

**Comment by harishankarv** [comment]
I have commented [here](https://github.com/kivy/pyjnius/issues/57#issuecomment-227886988) with this answer, but I am posting this here regardless. 

After wasting hours on how to set this up properly, this is what worked for me. I have tried to be as verbose as possible. <br>
1. Download and install jdk (if not installed)
    http://www.oracle.com/technetwork/java/javase/downloads/index.html
 
2. System/Environment Variables (replace  jdk1.7.0_79  with your jdk version )
    - Add to Environment Variables:
        * JDK_HOME C:\Program Files\Java\jdk1.7.0_79\
        * PATH C:\Program Files\Java\jdk1.7.0_79\jre\bin\server\
    - Add to System Variables:
        * PATH: C:\Program Files\Java\jdk1.7.0_79\bin\
 
3.	Install pip (if not installed)
    - https://pip.pypa.io/en/latest/installing/
 
4.	Install Cython (if not installed):
    - Install wheel: `pip install wheel`
    - Install cython:
        * Download cython for windows: http://www.lfd.uci.edu/~gohlke/pythonlibs/#cython
        * `pip install Cython-0.24-cp35-cp35m-win_amd64.whl` (use appropriate filename)
 
5.	Install  Microsoft Visual C++ Compiler for Python 2.7:
    - http://aka.ms/vcpython27 <br>
    Python modules can be part written in C (typically for speed).  If you try to install such a package with Pip (or setup.py), it has to compile that C/C++ from source.  Refer:
http://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat/26127562#26127562
    - Install setuptools for the compiler to work: <br>
https://pypi.python.org/pypi/setuptools#windows-simplified
 
6.	Download pyjnius source and install:
    - https://github.com/kivy/pyjnius
    - `python setup.py install`

**Comment by hamid1380** [comment]
hi
now I catch this error:

C:\Python27\pyjnius-master>python setup.py install
WARNING: Not able to assign machine() = AMD64 to a cpu value!
Using cpu = 'i386' instead!
C:\Python27\27\lib\site-packages\setuptools-24.0.3-py2.7.egg\setuptools\dist.py:
295: UserWarning: Normalizing '1.1-dev' to '1.1.dev0'
running install
running bdist_egg
running egg_info
writing requirements to jnius.egg-info\requires.txt
writing jnius.egg-info\PKG-INFO
writing top-level names to jnius.egg-info\top_level.txt
writing dependency_links to jnius.egg-info\dependency_links.txt
reading manifest file 'jnius.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*COPYING'
writing manifest file 'jnius.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
skipping 'jnius\jnius.c' Cython extension (up-to-date)
building 'jnius' extension
error: [Error 2] The system cannot find the file specified

**Comment by KeyWeeUsr** [comment]
Anaconda now comes with prebuilt packages and we have instructions directly for `conda` packages. Ref https://github.com/kivy/pyjnius/issues/122#issuecomment-459554674.
