### ISSUE TITLE
Pypi wheel for windows?

### ISSUE THREAD

**Issue by evbo** [kivy/pyjnius#148]
Hi, I'd like to install the latest and greatest pyjnius wheel on my windows 7 machine but can only find the wheel for 1.1 on Christoph Gohlke's site.

I notice there's wheels for mac and linux on Pypi... why not for windows?

I'd build pyjnius myself but I can't reinstall VS2010 or access the registry as needed to fix my C1083 known compiler issue: http://stackoverflow.com/questions/23297777/what-provides-microsoft-visual-studio-10-0-vc-include-io-h
##

**Comment by dessant** [comment]
New pypi releases are long overdue, but please note that the wheels you see here are not from us:
https://pypi.python.org/pypi/pyjnius

We intend to contact the owner of the fork, the official package being named `jnius` adds to the confusion: https://pypi.python.org/pypi/jnius.

It would be great to release this repo as `pyjnius` instead of the current `jnius` on pypi.

**Comment by KeyWeeUsr** [comment]
Tracking at #38.
