### ISSUE TITLE
Build non-trivial because of Cython

### ISSUE THREAD

**Issue by blootsvoets** [kivy/pyjnius#188]
Currently, users need to install Cython before installing the package (in a separate command). This can be slightly frustrating for automatic installs. If the c-files are added to the repository, users could compile those with distutils, without needing Cython at all. This setup is advised in
http://docs.cython.org/src/reference/compilation.html#distributing-cython-modules

Would that be feasible for this package?
##

**Comment by inclement** [comment]
I don't see a problem with doing this. I'm not familiar with best practice here, should the .c files perhaps only be in release versions, to avoid cluttering the repo and needing to keep them up to date?

**Comment by blootsvoets** [comment]
Possible approach for only doing this during releases:
http://stackoverflow.com/a/18418524/574082

**Comment by dessant** [comment]
Wheels are needed. :)

**Comment by blootsvoets** [comment]
Would fix #208.

**Comment by kived** [comment]
As you would still need a compiler, I fail to see how this would really make build less non-trivial. It wouldn't necessarily fix #208, and that's not a real issue anyway but something specific to that user's environment - that user has messed up his Python installation, most likely by assuming that you can use py3.4's site-packages dir with py3.5. Just because the immediate issue is the cython import doesn't mean there won't be a ton of other issues if that one is bypassed.

**Comment by Tomaat** [comment]
Is there any progress on this issue? Because I now have to install Cython before pyjnius, and have a project with pyjnius as a dependency, I also have to install Cython before installing my project (which makes deploying harder)
Is it not possible to add Cython to the INSTALL_REQUIRES in setup.py?
e.g. setup.py:64-78
```python
try:
    from Cython.Distutils import build_ext
    INSTALL_REQUIRES.append('cython')
except ImportError:
    # pylint: disable=ungrouped-imports
    try:
        from setuptools.command.build_ext import build_ext
    except ImportError:
        from distutils.command.build_ext import build_ext
    if PLATFORM != 'android':
        print('\n\nYou need Cython to compile Pyjnius.\n\n')
        raise
    # On Android we expect to see 'c' files lying about.
    # and we go ahead with the 'desktop' file? Odd.
    FILES = [fn[:-3] + 'c' for fn in FILES if fn.endswith('pyx')]
```
would become something like
```python
try:
    from setuptools.command.build_ext import build_ext
except ImportError:
    from distutils.command.build_ext import build_ext

if PLATFORM != 'android':
    INSTALL_REQUIRES.append('cython')
else:
    # On Android we expect to see 'c' files lying about.
    # and we go ahead with the 'desktop' file? Odd.
    FILES = [fn[:-3] + 'c' for fn in FILES if fn.endswith('pyx')]
```
I tried this on ubuntu18.4 with python 3.7.2 (a clean virtual env with setuptools 40.8.0 and pip 19.0.3) and it seems to work, but haven't tested thoroughly.

If you think this will be a solution, I can create a pull request.

**Comment by AbdealiJK** [comment]
The solution here is not to add it in `install_requires` but in `setup_requires`
`install_requires` is not available when the pip installation is happening (i.e. it is not installed when the setup.py is being run)
