### ISSUE TITLE
pyjunius on Windows Failed

### ISSUE THREAD

**Issue by ghost** [kivy/pyjnius#205]
Dear All,

When running this on iPython, Spyder, I have the following failing:

!pip install git+https://github.com/kivy/pyjnius --user

Message is :
gg should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+

Any kind of ideas ?
Thanks
##

**Comment by KeyWeeUsr** [comment]
You might want to try with the latest version on PyPI or even with the master branch directly. If you try to install from github, use `pip install https://github.com/kivy/pyjnius/zipball/<branch or tag>` instead of `git+`. Open a new issue with logs and more verbose details if the issue still persists.
