### ISSUE TITLE
import jnius fails: "No Java runtime present, requesting install"

### ISSUE THREAD

**Issue by muupan** [kivy/pyjnius#277]
Hi, I installed pyjnius via pip but when I `import jnius` the python interpreter crashes saying "No Java runtime present, requesting install." with a pop-up window saying "To open "this Java application" you need to install the legacy Java SE 6 runtime."

I also tried building from the source, but `make tests` failed with the same messages.

OSX El Capitan 10.11.6
Python 3.5.1
```
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
$ echo $JDK_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
$ python
Python 3.5.1 |Anaconda custom (x86_64)| (default, Dec  7 2015, 11:24:55)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jnius
No Java runtime present, requesting install.
```

**Comment by muupan** [comment]
This issue was solved by adding `<string>JNI</string>` to `JVMCapabilities` in `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Info.plist` as suggested in https://github.com/joeferner/node-java/issues/90.

**Comment by ctrueden** [comment]
There is another, better way to avoid this horrible issue: load `libjli` before loading `libjvm`. The ImageJ project [uses this trick for its launcher](https://github.com/imagej/imagej-launcher/commit/efaea16049ded0adba625238bf9c769798c4a18a) successfully. And [here is another example of a project using this solution](https://github.com/xamarin/java.interop/pull/198). A big advantage of this approach is that users do not need to manually tweak their Java installations in order to get up and running.

@KeyWeeUsr @tshirtman The ImageJ project's [Python integration](https://github.com/imagej/pyimagej) (built on pyjnius) would benefit from this fix being implemented here. I can do a PR if it would be helpful—please let me know!

**Comment by ctrueden** [comment]
@KeyWeeUsr @tshirtman  I filed PR #441. Please take a look—it makes macOS behavior much better!
