### ISSUE TITLE
How to create a writable java byte[] array or short[] array in python?

### ISSUE THREAD

**Issue by xiongyihui** [kivy/pyjnius#296]
I'm trying to use jnius with Android `AudioRecord` to read audio data. The `AudioRecord` has:

```
int read (byte[] audioData, 
                int offsetInBytes, 
                int sizeInBytes, 
                int readMode)
```

How to create a `byte[]` variable and pass it to the `read` function?

**Comment by KeyWeeUsr** [comment]
Generally it's easier to try and replicate the signature with something simple instead of trying to just plug it into a big API set. For example:

```java
public class TestApp {
    public static void main(String[] args) {
        test("Some string".getBytes());
    }

    public static void test(byte[] array) {
        for (int i = 0; i < array.length; i++) {
            System.out.println(array[i]);
        }
    }
}
```

which if `autoclass()`ed can take from my Python 3 interpreter both `b'Some string'` and `bytearray(b'Some string')`.

Basic Python types conversion is handled in [`jnius_conversion.pxi`](https://github.com/kivy/pyjnius/blob/master/jnius/jnius_conversion.pxi), therefore more non-standard Python types conversion you'll see there too.
