### ISSUE TITLE
flask hang when using pyjnius in the 35th time (centos 7.2.1511)

### ISSUE THREAD

**Issue by sunqing94** [kivy/pyjnius#333]
Cython==0.27.3
pyjnius==1.1.1
centos 7.2.1511 (centos 6 doesn't happen)

In my flask project, I use pyjnius to invoke a java method in jar package to decrypt  a token, like this:
```
from jnius import autoclass
def decrypt_by_default_public_key(token):
        rsa = autoclass("XX.XX.XX.XX") 
        public_key = "XXXXXXX"
        rsa.decryptByPublicKey(token, public_key)
```
when I invoke the method `decrypt_by_default_public_key` in 35th time, my flask app hanged but the thread and process state seemed ok, also the cpu memory and io state. 
when I change the code like this:
```
def decrypt_by_default_public_key(token):
        from jnius import autoclass
        rsa = autoclass("XX.XX.XX.XX")
        public_key = "XXXXXXX"
        rsa.decryptByPublicKey(token, public_key)
```
the problem disappeared!
please investigate and fix this problem, thanks!

**Comment by KeyWeeUsr** [comment]
There is no code to reproduce it, you just move the import, however for me it seems like your `.jar` file causes troubles when someone wants to load your class multiple times. To actually investigate we'll need an example that reproduces the problem.

In case you have a simple Java code that I can compile to `.jar`, please add it to the issue. Otherwise, I've tried multiple Java classes with and without wrapping them into functions in the same shape you provided e.g.:

```python
from jnius import autoclass

def test():
    autoclass('SomeClass').static_method('arg')

while True:
    test()
```

and let it run for 5 minutes. No errors, hangs, crashes.
