### ISSUE TITLE
import jnius fail in windows python environment 

### ISSUE THREAD

**Issue by CQ-HC** [kivy/pyjnius#388]
After using ‘pip install pyjnius’ successfully，i use 'import jnius' in python, the following problem occurs.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\jnius\__init__.py", line 22, in <module>
    class PythonJavaClass_(with_metaclass(MetaJavaBase, PythonJavaClass)):
NameError: name 'MetaJavaBase' is not defined

**Comment by KeyWeeUsr** [comment]
There is no such thing as `jnius_init_.py`, however it seems like the `jnius/__init__.py` that loads the extension `jnius.pyx` (`jnius.so` or similar name after compilation) could not import the stuff from the extension. That's most likely due to bad compilation.

Make sure you have a compiler present and paste a full log from `pip install -v pyjnius` in case the issue still persists.

**Comment by CQ-HC** [comment]
@KeyWeeUsr 
Thank you very much for analyzing the reasons for me.So, I uninstalled the jnius package and reinstalled it to solve the problem.

**Comment by yangjingScarlett** [comment]
Have you fixed this problem? I met the same "name 'MetaJavaBase' is not defined" error and I cannot solve it by reinstalling the jnius package

**Comment by tshirtman** [comment]
hello, did you install recently? Because it should install from a wheel now, which means you don't have anything to compile on your machine, if pip installed from the wheels, can you say which version of python you used?
