### ISSUE TITLE
 is it possible to use annotation in jnius?

### ISSUE THREAD

**Issue by FranciscoCarbonell** [kivy/pyjnius#391]
is it possible to use annotation in jnius?

@JavascriptInterface
def interface():
    ....
   ......

**Comment by KeyWeeUsr** [comment]
PyJNIus is for **Java**, not Java**script**, so that surely is a no. Anyway, you can't do that even for the ordinary Java interface because there is no such implementation that would wrap your function into a class because in Java an interface is a **class**. That's why one of the approaches is with the list of Java interfaces your `PythonJavaClass` implements e.g. [here](https://pyjnius.readthedocs.io/en/latest/api.html?highlight=javainterface#jnius.PythonJavaClass).
