### ISSUE TITLE
Invalid static method resolution

### ISSUE THREAD

**Issue by vruusmann** [kivy/pyjnius#408]
I have a class hierarchy, where class `Child` extends class `Parent`, and they both define a method "newInstance":
```java
class Parent {
  static
  public Parent newInstance(){
    return new Parent();
  }
}

class Child extends Parent {
  static
  public Child newInstance(){
    return new Child();
  }
}
```

I'm trying to obtain a new `Child` instance by invoking the static method `Child#newInstance()`. However, I keep getting `Parent` instances (instead of `Child` instances), which indicates that PyJNIus has "redirected" my static method invocation to `Parent#newInstance()`. This is obviously incorrect behaviour.

Using PyJNIus version 1.2.0.

**Comment by tshirtman** [comment]
From what i gather (didn't look at this code in some time), we use Class.getMethods() to populate our list of methods, 
https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#getMethods()
and if we have multiple signatures for the same name, we use JavaMultipleMethod, and use `compute_score` at runtime to determine which method to call depending on various parameters, but…
https://github.com/kivy/pyjnius/blob/5f6aa738b2b7ae496ec43bfadbf9933ee640bb7b/jnius/jnius_utils.pxi#L340-L352

i think this should try to give less points the further in the class hierarchy of classes the method come from, because the previously mentioned `getMethods` method makes no promise on the order of the returned list, we might currently return any implementation, not necessarily the one the programmer expect.

**Comment by vruusmann** [comment]
One could do `Class#getDeclaredMethods()`, and then move up the class hierarchy. The first method that is found should be returned.

Please note that this issue is specifically about static methods. The resolution of instance methods is a bit more complicated, and should probably follow the existing logic.

**Comment by tshirtman** [comment]
Right, though for this i think the logic is not very different, as seen in `__call__` of JavaMultipleMethod. 
https://github.com/kivy/pyjnius/blob/5f6aa738b2b7ae496ec43bfadbf9933ee640bb7b/jnius/jnius_export_class.pxi#L1011-L1044

**Comment by vruusmann** [comment]
For a bit of a context, I ran into this method resolution here:
https://github.com/jpmml/jpmml-evaluator-python/commit/27f4a126b3eb0a81b50ec83d3c85cb4636697d50

My class hierarchy is `class ReportingValueFactoryFactory extends ValueFactoryFactory`; both the parent and children have this "newInstance" static method.

In Java (and Py4J), the expression `ReportingValueFactoryFactory#newInstance()` gives me a `ReportingValueFactoryFactory` instance. However, PyJNIus 1.2.0 gives me `ValueFactoryFactory`, and my unit test fails.
https://github.com/jpmml/jpmml-evaluator-python/commit/27f4a126b3eb0a81b50ec83d3c85cb4636697d50#diff-8bae942a7b997446bb297daf2ff5dca7R104

**Comment by tshirtman** [comment]
Yeah, I think recursive calls to `getDeclaredMethods` could work, making sure to never override a method with the same (name, signature). It would change https://github.com/kivy/pyjnius/blob/5f6aa738b2b7ae496ec43bfadbf9933ee640bb7b/jnius/reflect.py#L171-L220 a bit, but should fix the issue.

**Comment by tshirtman** [comment]
I have a tentative fix in branch fix/method_order_inheritance if you want to give a try, it builds and the existing tests pass here, but it would be better to add your Parent/Child case as a new test, to be sure.

**Comment by vruusmann** [comment]
@tshirtman Can confirm that #409 (obtained via `git fetch origin pull/409/head:method_order_inheritance`, and then built/installed locally) fixes this issue (and does not seem to cause any new issues).

**Comment by tshirtman** [comment]
Thank you for confirmation, i'll try adding the test case later, so we can avoid regressions :), then merge.
