### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment # Problematic frame: # C  [jnius.cpython-38-x86_64-linux-gnu.so+0x12d74]  __Pyx_PyObject_GetAttrStr+0x4

### ISSUE THREAD

**Issue by Aashish07** [kivy/pyjnius#611]

**Comment by Aashish07** [comment]
Sometimes the system crashes  and sometimes it doesn't. 
I am copying the log trace file. 
[hs_err_pid3868.log](https://github.com/kivy/pyjnius/files/7543307/hs_err_pid3868.log)

**Comment by cmacdonald** [comment]
Top frame is:
```
j  org.jnius.NativeInvocationHandler.invoke0(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;+0
```

In my experience, this can ALWAYS be explained by passing a Python object into the Java, where its lifetime in Java exceeds that in Python. In this case, I see you have a thread; so probably the Thread is dealing with a Python object that has since been GC'd by Python. The trick is to hold a Python reference for the lifetime of the object in Java.

**Comment by cmacdonald** [comment]
Did this hint help?

**Comment by Aashish07** [comment]
this is working beneath the wrapper, which is not in control. This hint looks like a obvious explanation to the issue, but , its application is not in the scope.

**Comment by cmacdonald** [comment]
I dont know which wrapper code to which you refer, but as a general usage of Jnius, it can be considered a bug if it lets a Python object go out of scope while the JVM holds a reference to its corresponding proxy object.
