### ISSUE TITLE
run method of Runnable implementation gets called in thread correctly?

### ISSUE THREAD

**Issue by knappador** [kivy/pyjnius#79]
This code snippet really looks like it should work, but the run method on _AsyncCall...I can't tell if it's ever running.  Is it broken?

I'm looking at using AsyncTask as a (better) workaround.  I don't think it can't be done in pure PyJNIus because it requires subclassing and I don't see how we do that with PyJNIus yet.

``` python

from jnius import autoclass, PythonJavaClass, java_method
Thread = autoclass('java.lang.Thread')

class _AsyncMethod(PythonJavaClass):
    __javainterfaces__=['java.lang.Runnable']
    __javacontext__='app'

    @java_method('()V')
    def run(self):
        for i in range(10):
            Logger.info('Hey this thread is good spinning')

t = Thread(_AsyncMethod())
Logger.info(str(t.isAlive()))  #false
t.start()
Logger.info(str(t.isAlive()))  #true
t.join()
Logger.info(str(t.isAlive()))  #false

# never prints anything in logcat

```
##

**Comment by Julian-O** [comment]
We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to this project. This issue is being closed, because it doesn't describe a bug in this project.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).

Of course, if it turns out you have stumbled over a bug in this project, we do want to hear about it here. The support channels should be able to help you craft an appropriate bug report.
